apiVersion: v2
name: cost-onprem
description: Jon Keams Cost Management On-Premise solution for OpenShift that maps to v0.3.0
type: application
version: 0.0.1
appVersion: "0.0.1"

keywords:
  - cost-management
  - resource-optimization
  - openshift
  - on-premise

maintainers:
  - name: Insights On-Premise Team

dependencies: []

